# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
      args: [ '--maxkb=512', '--enforce-all' ]
      exclude: conda-lock.yml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff  # Run the linter
      args: [ --fix ]
      types_or: [ python, pyi ]
    - id: ruff  # Run the linter for Jupyter notebooks with the PLR0913 rule ignored
      args: [ --fix, --ignore=PLR0913 ]
      types: [ jupyter ]
    - id: ruff-format  # Run the formatter
      types_or: [ python, pyi, jupyter ]

# https://pre-commit.ci/#configuration
ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
