name: claymodel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-lock~=2.5.6
  - einops~=0.7.0
  - fiona~=1.9.5
  - geopandas-base~=0.14.1
  - h5netcdf~=1.3.0
  - jupyter-book~=1.0.0
  - jupyterlab~=4.0.7
  - jsonargparse~=4.27.0
  - lightning~=2.1.0
  - matplotlib-base~=3.8.2
  - planetary-computer~=1.0.0
  - python-box~=7.1.0
  - pytorch~=2.1.0  # [osx]
  - pytorch~=2.1.0 *cuda12*  # [linux]
  - python~=3.11.0
  - pyarrow~=16.1.0
  - rioxarray~=0.15.0
  - rasterio~=1.3.10
  - s3fs~=2024.3.1
  - scikit-image~=0.22.0
  - scikit-learn~=1.4.0
  - stackstac~=0.5.0
  - timm~=0.9.16
  - torchdata~=0.7.1
  - torchvision~=0.16.1
  - transformers~=4.35.2
  - typeshed-client~=2.4.0
  - vit-pytorch~=1.6.4
  - wandb~=0.15.12
  - zarr~=2.16.1
platforms:
  - linux-64
