name: claymodel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-lock~=2.5.1
  - einops~=0.7.0
  - fiona~=1.9.5
  - geopandas-base~=0.14.1
  - h5netcdf~=1.3.0
  - jupyter-book~=0.15.1
  - jupyterlab~=4.0.7
  - jsonargparse~=4.27.0
  - lightning~=2.1.0
  - matplotlib-base~=3.8.2
  - planetary-computer~=1.0.0
  - pytorch~=2.1.0=*cuda120*
  - python=3.11
  - rioxarray~=0.15.0
  - scikit-image~=0.22.0
  - stackstac~=0.5.0
  - torchdata~=0.7.1
  - transformers~=4.35.2
  - typeshed-client~=2.4.0
  - vit-pytorch~=1.6.4
  - wandb~=0.15.12
  - zarr~=2.16.1
