# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Clay Foundation Model
author: Clay Foundation
logo: logo.png
only_build_toc_files: true

# Only execution notebooks with no output cells on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  exclude_patterns:
    - clay-v0-*.ipynb
    - partial-inputs.ipynb
    - tutorial_digital_earth_pacific_patch_level.ipynb
    - patch_level_cloud_cover.ipynb

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: clay_foundation_model.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org

# Information about where the book exists on the web
repository:
  url: https://github.com/Clay-foundation/model  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />
    This content is licensed under a
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

sphinx:
  config:
    html_show_copyright: false
  extra_extensions:
    - 'sphinx.ext.autodoc'
